### ISSUE TITLE
Can't run docker-compose with watcher as documented

### ISSUE THREAD

**Issue by deisi** [jbarlow83/OCRmyPDF#498]
**Describe the issue**

The Documentation for the docker container with docker-compose as stated in https://ocrmypdf.readthedocs.io/en/latest/batch.html#hot-watched-folders doesn't work. 

**To Reproduce**
Make docker-compose.yml file with

``` yaml
---
ocrmypdf:
  restart: always
  container_name: ocrmypdf
  image: jbarlow83/ocrmypdf
  volumes:
    - '/media/scan:/input'
    - '/mnt/scan:/output'
  environment:
    - OCR_OUTPUT_DIRECTORY_YEAR_MONT=0
  entrypoint:
    - python3:
      command: "watcher.py"
```

Run `docker-compose up'  results in 
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
ocrmypdf.entrypoint contains {"python3": null, "command": "watcher.py"}, which is an invalid type, it should be a string

```

**Expected behavior**

Should run.

**System:**

- OS: Ubuntu19.10
- jbarlow83/ocrmypdf from docker-hub

**Additional context**

The docker run command from the documentation with the watcher on works. It clearly is the entrypoint syntax that has an isse here. I have tried to get it to work, but for now it is always failing. I tired e.g.
``` yaml
entrypoint: python3 watcher.py
```

But that fails with file not found errors. However an `ls` shows that `watcher.py` is available. Using an absolute python3 path has also not worked for me.

**Comment by deisi** [comment]
Okay, I made it work. The docker-compose file needs to look like:

``` yaml
---
ocrmypdf:
  restart: always
  container_name: ocrmypdf
  image: jbarlow83/ocrmypdf
  volumes:
    - '/volume1/public/scans/text:/input'
    - '/volume1/public/scans/ocr:/output'
  environment:
    - OCR_OUTPUT_DIRECTORY_YEAR_MONT=0
  entrypoint: python3
  command: watcher.py

```
