### ISSUE TITLE
Error logged in Docker container every 60 seconds

### ISSUE THREAD

**Issue by pedropombeiro** [jbarlow83/OCRmyPDF#731]
**Describe the bug**

When running the docker image with the Loki logging driver, I notice a recurrent pair of errors being logged every minute to STDOUT. The rest of the OCRmyPDF output is sent to STDERR:

```
  |   | 2021-02-10 22:53:33 | Input Directory: /input
  |   | 2021-02-10 22:53:33 | Output Directory: /output
  |   | 2021-02-10 22:53:33 | Output Directory Year & Month: True
  |   | 2021-02-10 22:53:44 | python3: can't open file 'bash': [Errno 2] No such file or directory
  |   | 2021-02-10 22:53:44 | python3: can't open file 'sh': [Errno 2] No such file or directory
  |   | 2021-02-10 22:54:44 | python3: can't open file 'bash': [Errno 2] No such file or directory
  |   | 2021-02-10 22:54:45 | python3: can't open file 'sh': [Errno 2] No such file or directory
  |   | 2021-02-10 22:55:44 | python3: can't open file 'bash': [Errno 2] No such file or directory
  |   | 2021-02-10 22:55:45 | python3: can't open file 'sh': [Errno 2] No such file or directory
```

When I try the same with the default logging driver, these errors don't show up in the log. I believe not because they don't happen, but because `docker logs` is not showing STDOUT output.

**To Reproduce**

Use the following `docker-compose.yml` file, with a Loki instance running at `localhost:3100`:

```yaml
version: "2.2"
services:
  OCRmyPDF:
    image: jbarlow83/ocrmypdf
    init: true
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        loki-external-labels: job=dockerlogs
        loki-relabel-config: |
          - action: labeldrop
            regex: filename
    networks: []
    volumes:
      - ${pathToCrawl1}/Others:/output
      - ${inboxPath}:/input
    environment:
      - OCR_OUTPUT_DIRECTORY_YEAR_MONTH=1
      - OCR_USE_POLLING=1
      - OCR_POLL_NEW_FILE_SECONDS=60
      - OCR_ON_SUCCESS_DELETE=1
      - OCR_DESKEW=1
      - 'OCR_JSON_SETTINGS={"force_ocr": true}'
      - PYTHONUNBUFFERED=1
    entrypoint: python3
    command: watcher.py
```

**Expected behavior**
I would like to know what is causing these regular calls to `bash` and `sh`, and ideally get rid of them, as it doesn't seem to be something that is desired.

**System (please complete the following information):**
 - OS: QNAP QTS 4.5.2.1266
 - Python version: 3
 - OCRmyPDF version: v11.6.0

**Installation**
How did you install OCRmyPDF? Did you install it from your operating system's
package manager, or using pip?

Docker.

**Additional context**

Removing `OCR_USE_POLLING` does not get rid of the errors.
